name: sfrd_ios
description: "RWC - Media Production Mobile App untuk iOS & Multiplatform."
publish_to: "none"
version: 8.8.11+891

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # UI, Icons, and Components
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  cached_network_image: ^3.4.1
  intl: any

  # Hardware, Media, & ML
  camera: ^0.11.0+2
  image_picker: ^1.1.2
  google_mlkit_face_detection: ^0.12.0
  google_mlkit_text_recognition: ^0.14.0

  # Networking, Storage & Utilities
  http: ^1.2.2
  url_launcher: ^6.3.0
  shared_preferences: ^2.3.2
  path_provider: ^2.1.4
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
